fastlane_require "dotenv"

before_all do 
  Dotenv.load ".env.secret"
end

#this will create app in appconnect
desc "Create app on dev portal"
lane :create_app do 
  create_app_online # produce
end


default_platform(:ios)
platform :ios do

  desc "Sync signing"
  lane :signing do 
    sync_code_signing # match

    #This is provisioning profile mapping, 
    #will pull certificates and profiles and change them in excode
    mapping = Actions.lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]

    update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end

  desc "Build binary"
  lane :build do 
    # signing
    build_ios_app # gyme
  end

  desc "Release "
  lane :release do 
    build
    upload_to_app_store # deliver
  end


  # desc "Export our app"
  # lane :export_app do 
  #   build_app(
  #     project: "DemoFastlane.xcodeproj",
  #     scheme: "DemoFastlane",
  #     clean: true,
  #     export_xcargs: "-allowProvisioningUpdates",
  #     output_name: "ReleaseAppFL.ipa"
  #   ) #or call gym instead of build_app
  # end

  # desc "Deliver our app"
  # lane :upload_app do 
  #   deliver(
  #     ipa: "ReleaseAppFL.ipa",
  #     skip_screenshots: true,
  #     skip_metadata: true,
  #     skip_app_version_update: true,
  #     force: true #will send without giving html screen of the app vor validation      
  #   )
  # end

  # desc "Release our app to app store"
  # lane :release_app do 
  #   export_app
  #   upload_app
  # end
end



